# Generate the two headers a ported module needs from its build:
#
#   RackPluginConfig.h     the plugin-wide metadata (id prefix, category,
#                         vendor) the adaptor uses for automatic registration
#   RackPanelResources.h   every res/*.svg, registered with rack::PanelRegistry
#                         under the path the module names in createPanel()
#
# Both are generated rather than passed as -D defines. Values like
# "VCV (ported)" do not survive the trip: MSBuild splits its
# PreprocessorDefinitions on semicolons and mangles parentheses, and the
# failure surfaces as a syntax error deep inside a header. A generated file
# has no quoting layer to lose.
#
#   rack_module_resources(<target> <res-dir>)
#
# Metadata comes from these variables, set once at the top level:
#   RACK_MODULE_ID_PREFIX   default "VCV: "
#   RACK_MODULE_CATEGORY    default "VCV"
#   RACK_MODULE_VENDOR      default "VCV (ported)"

function(rack_module_resources TARGET RES_DIR)
    # Keyed by TARGET, not just the calling directory: the static build
    # (static_library/) creates every module's target from ONE directory
    # scope, and a shared "generated" dir would have all of them overwriting
    # each other's RackPanelResources.h. The .gmpi build called this from one
    # directory per module, so for it this only moves the path.
    set(GENERATED_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated/${TARGET}")

    if(NOT DEFINED RACK_MODULE_ID_PREFIX)
        set(RACK_MODULE_ID_PREFIX "VCV: ")
    endif()
    if(NOT DEFINED RACK_MODULE_CATEGORY)
        set(RACK_MODULE_CATEGORY "VCV")
    endif()
    if(NOT DEFINED RACK_MODULE_VENDOR)
        set(RACK_MODULE_VENDOR "VCV (ported)")
    endif()

    # --- plugin metadata ---------------------------------------------------
    set(CONFIG "// GENERATED by rack_module_resources() - do not edit.\n")
    string(APPEND CONFIG "#pragma once\n\n")
    string(APPEND CONFIG "#define RACK_MODULE_ID_PREFIX \"${RACK_MODULE_ID_PREFIX}\"\n")
    string(APPEND CONFIG "#define RACK_MODULE_CATEGORY  \"${RACK_MODULE_CATEGORY}\"\n")
    string(APPEND CONFIG "#define RACK_MODULE_VENDOR    \"${RACK_MODULE_VENDOR}\"\n")

    file(GENERATE OUTPUT "${GENERATED_DIR}/RackPluginConfig.h" CONTENT "${CONFIG}")

    # --- panel art ---------------------------------------------------------
    file(GLOB PANEL_SVGS CONFIGURE_DEPENDS "${RES_DIR}/*.svg")

    # The registration variables are STATIC (internal linkage) and NAMED PER
    # TARGET, and the first of those is load-bearing. They used to be
    # `inline const bool panel0`, which was fine while every module was its
    # own binary - but the static build links all 38 modules into ONE, and
    # inline variables with the same name COLLAPSE to a single copy at link,
    # so exactly one module's panel registered and the other 37 fell back to
    # the 100x100 default, artless. static gives each TU its own; the unique
    # name is belt and braces on top.
    string(MAKE_C_IDENTIFIER "${TARGET}" SAFE_TARGET)

    set(PANELS "// GENERATED by rack_module_resources() - do not edit.\n")
    string(APPEND PANELS "#pragma once\n\n#include \"plugin.hpp\"\n\n")
    string(APPEND PANELS "namespace rack { namespace generated_panels {\n\n")

    set(INDEX 0)
    foreach(SVG ${PANEL_SVGS})
        get_filename_component(SVG_NAME "${SVG}" NAME)
        file(READ "${SVG}" SVG_TEXT)

        # The delimiter is long on purpose: a raw string ends at the first
        # )<delim>" and SVG path data is full of plain )" pairs.
        string(APPEND PANELS
            "[[maybe_unused]] static const bool panel_${SAFE_TARGET}_${INDEX} = PanelRegistry::instance().add(\n"
            "    \"res/${SVG_NAME}\",\n"
            "    R\"RACK_PANEL_SVG(${SVG_TEXT})RACK_PANEL_SVG\");\n\n")

        math(EXPR INDEX "${INDEX} + 1")
    endforeach()

    string(APPEND PANELS "}} // namespace rack::generated_panels\n")

    file(GENERATE OUTPUT "${GENERATED_DIR}/RackPanelResources.h" CONTENT "${PANELS}")

    target_include_directories(${TARGET} PRIVATE "${GENERATED_DIR}")

    # Only header NAMES cross the command line - no spaces, nothing to mangle.
    target_compile_definitions(${TARGET} PRIVATE
        RACK_PLUGIN_CONFIG_HEADER="RackPluginConfig.h"
        RACK_PANEL_RESOURCES_HEADER="RackPanelResources.h")

    message(STATUS "rack_module_resources(${TARGET}): ${INDEX} panel(s) from ${RES_DIR}")
endfunction()
